[project]
name = "autodos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fschat==0.2.36",
    "httpx==0.27.2",
    "openai==1.41.1",
    "pandas==2.2.0",
    "requests==2.31.0",
    "structlog==24.4.0",
]
